const routes = {
  HomePage: '/',
  TypographyPage: '/typography',
  ButtonPage: '/buttons',
  TextFieldPage: '/textfield',
  SelectPage: '/select',
  RadioButtonPage: '/radiobutton',
  CheckboxPage: '/checkbox',
  SwitchPage: '/switch',
  RatingPage: '/rating',
  AutocompletePage: '/autocomplete',
  LayoutPage: '/layout',
  CardPage: '/card',
  AccordionPage: '/accordion',
  ImageListPage: '/imagelist',
  NavbarPage: '/navbar',
  LinkPage: '/link',
  BreadcrumbsPage: '/breadcrumbs',
  DrawerPage: '/drawer',
  SpeedDialPage: '/speeddial',
  BottomNavigationPage: '/bottomnavigation',
  AvatarPage: '/avatar',
} as const;

export default routes;
